# Generated by Django 5.1.4 on 2024-12-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('avatar', models.CharField(default='default_avatar.png', max_length=255)),
                ('role', models.CharField(default='USER', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
