# Generated by Django 5.1.4 on 2025-01-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AddField(
            model_name='data',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
