# Generated by Django 5.1.4 on 2025-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_doctor_data_img_data_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='birthDay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='isBooking',
            field=models.BooleanField(default=False),
        ),
    ]
