# Generated by Django 5.1.4 on 2025-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_data_address_data_birthday_data_isbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('forAnother', models.BooleanField(default=False)),
                ('remark', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='birthDay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='isBooking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
