# Generated by Django 5.1.4 on 2025-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_booking_status_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
