# Generated by Django 5.1.4 on 2024-12-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_data_groups_data_is_active_data_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='data',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='data',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='data',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='data',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='data',
            name='avatar',
            field=models.CharField(default='default_avatar.png', max_length=255),
        ),
        migrations.AddField(
            model_name='data',
            name='role',
            field=models.CharField(default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
