# Generated by Django 5.1.4 on 2025-02-10 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_result_doctor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Doctor_phone',
            field=models.CharField(default='Unknown Phone', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='work',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
