# Generated by Django 5.1.4 on 2024-12-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='User',
        ),
    ]
